name: cheat-snap
version: '2.2.2'
summary: cheat lets you to create and view interactive cheatsheets on the command-line.
description: |
  cheat allows you to create and view interactive cheatsheets on the
  command-line. It was designed to help remind *nix system administrators of
  options for commands that they use frequently, but not frequently enough to
  remember.

grade: stable
confinement: strict

apps:
  cheat:
    command: cheat

parts:
  cheat:
    source: https://github.com/chrisallenlane/cheat.git
    source-tag: 2.2.2
    plugin: python
    python-packages:
      - docopt
      - pygments
      - appdirs
